services:
  app:
    build: .
    container_name: app
    ports:
      - "80:80"
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql